services:

  db:
    image: postgis/postgis:13-3.2-alpine
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data:Z
    ports:
      - "5431:5432"
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  actinia-core:
    build:
        context: ./actinia
        dockerfile: Dockerfile
    volumes:
      - ./actinia-core-data/grassdb:/actinia_core/grassdb:Z
      - ./actinia-core-data/userdata:/actinia_core/userdata
      - ./actinia-core-data/pgpass:/mnt/pgpass:Z
      - ./actinia-core-data/geodata_dir:/mnt/geodata:Z
      - ./actinia-core-data/workspace/temp_db:/actinia_core/workspace/temp_db
      - ./actinia-core-data/workspace/tmp:/actinia_core/workspace/tmp
      - ./actinia-core-data/resources:/actinia_core/resources

      # - *services-volume
    restart: always
    ports:
      - "8088:8088"
      - "5439:5432"
    depends_on:
      - redis

  redis:
    image: redis:5.0.4-alpine
    volumes:
      - ./redis_config:/data/
    environment:
      - REDIS_PASS_FILE=/data/.redis
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/redis.conf"
      --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    ports:
        - "6379:6379"

  django-redis-cache:
    image: redis:5.0.4-alpine
    volumes:
      - ./redis_config:/data/
    environment:
      - REDIS_PASS_FILE=/data/.redis
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/redis.conf"
      --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    ports:
        - "6370:6370"

  # api:
  #   build:
  #     context: ./openplains_api
  #   command: bash -c "python manage.py runserver 0.0.0.0:8005"
  #   volumes:
  #     - ./openplains_api:/code
  #     - ./actinia-core-data/resources:/actinia_core/resources:Z

  #   ports:
  #     - "8005:8005"
  #     - "8010:8010"
  #   depends_on:
  #     - db
  #     - actinia-core
  #     - django-redis-cache

  # celery_worker:
  #   build:
  #     context: ./openplains_api
  #   command: celery -A api.celery worker --loglevel=INFO
  #   volumes:
  #     - ./openplains_api:/code
  #   env_file:
  #     - ./openplains_api/api/.env
  #   depends_on:
  #     - redis
  #     - db
  #     - api
