# Generated by Django 4.2.7 on 2023-11-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grass", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.RemoveField(
            model_name="team",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="team",
            name="owner",
        ),
        migrations.RemoveConstraint(
            model_name="location",
            name="unique_location",
        ),
        migrations.RemoveField(
            model_name="location",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="location",
            name="teams",
        ),
        migrations.RemoveField(
            model_name="mapset",
            name="organization",
        ),
        migrations.AddField(
            model_name="token",
            name="api_key",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="token",
            name="actinia_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actinia_tokens",
                to="grass.actiniauser",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="expires",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("US", "user"),
                    ("TK", "task"),
                    ("TL", "Tangible Landscape"),
                    ("AP", "Application"),
                    ("AC", "Actinia"),
                ],
                default="US",
                max_length=2,
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("name", "epsg", "owner"), name="unique_location"
            ),
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
