# Generated by Django 4.2.7 on 2023-11-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grass", "0004_location_users_alter_mapset_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone", models.IntegerField()),
                ("projection", models.IntegerField()),
                ("n", models.FloatField()),
                ("s", models.FloatField()),
                ("e", models.FloatField()),
                ("w", models.FloatField()),
                ("t", models.FloatField()),
                ("b", models.FloatField()),
                ("nsres", models.FloatField()),
                ("ewres", models.FloatField()),
                ("nsres3", models.FloatField()),
                ("ewres3", models.FloatField()),
                ("tbres", models.FloatField()),
                ("rows", models.FloatField()),
                ("cols", models.FloatField()),
                ("rows3", models.FloatField()),
                ("cols3", models.FloatField()),
                ("depths", models.FloatField()),
                ("cells", models.FloatField()),
                ("cells3", models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name="location",
            old_name="users",
            new_name="actinia_users",
        ),
    ]
