# Generated by Django 4.2.7 on 2024-03-18 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("grass", "0007_alter_location_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mapset",
            name="unique_mapset",
        ),
        migrations.AlterUniqueTogether(
            name="mapset",
            unique_together={("name", "location", "owner")},
        ),
    ]
