# Generated by Django 4.2.7 on 2024-03-18 19:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("grass", "0008_remove_mapset_unique_mapset_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="location",
            name="unique_location",
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("name", "epsg", "owner")},
        ),
    ]
