###############################################################################
# Filename: OutputParameterExportSerializer.py                                 #
# Project: OpenPlains Inc.                                                     #
# File Created: Sunday December 17th 2023                                      #
# Author: Corey White (smortopahri@gmail.com)                                  #
# Maintainer: Corey White                                                      #
# -----                                                                        #
# Last Modified: Sun Dec 17 2023                                               #
# Modified By: Corey White                                                     #
# -----                                                                        #
# License: GPLv3                                                               #
#                                                                              #
# Copyright (c) 2023 OpenPlains Inc.                                           #
#                                                                              #
# django-actinia is an open-source django app that allows for with             #
# the Actinia REST API for GRASS GIS for distributed computational tasks.      #
#                                                                              #
# This program is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# This program is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with this program.  If not, see <https://www.gnu.org/licenses/>.       #
#                                                                              #
###############################################################################

from rest_framework import serializers


class OutputParameterExportSerializer(serializers.Serializer):
    """
    Serializer for the export output parameter.

    Attributes:
        format (str): The format of the output file in case of raster, strds, vector layer or text file export. Raster layer export supports only GTiff and COG format, STRDS layer export supports only GTiff format and all other formats are vector layer export formats. If the PostgeSQL format was chosen, a postgis database string dbstring must be provided so that the GRASS GIS module *v.out.ogr knows to which PostgreSQL database it should be connect. The name of the output layer can be specified as output_layer for PostgreSQL database exports. Some GRASS GIS modules allow the export of text files. These files can be exported and provided as downloadable link as well..
        type (str): The type of the output. In case of the file option only text files are supported for export. In addition the $file::unique_id option must be used in the value parameter to export a file that was generated by a GRASS GIS module. Exported text and vector files will always be compressed with zip.
        dbstring (str, optional): The database string to be used to connect to a PostgreSQL database for vector export.
        output_layer (str, optional): Name for output PostgreSQL layer. If not specified, GRASS GIS vector map layer name is used.
    """

    format = serializers.CharField()
    type = serializers.CharField()
    dbstring = serializers.CharField(required=False)
    output_layer = serializers.CharField(required=False)
