name: django-actinia tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: sudo apt-get install -y gdal-bin libgdal-dev

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install GDAL==`gdal-config --version`
        pip install -r requirements-dev.txt
    - name: Build Package
      run : |
        python setup.py sdist
        pip install -e .

    - name: Run Tests
      run: |
        python manage.py test
